version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template >
              /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'

  app:
    build:
      context: ./
      dockerfile: Dockerfile-App_2_5_9
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=db:${DATABASE_PORT}
    volumes:
      - ./${APP_PATH}:/app
    command: /bin/bash -c
      'sleep 45
      && rails db:migrate RAILS_ENV=production
      && rails s -p 3000 -b "0.0.0.0" --environment production'
    depends_on:
      - db

  db:
    image: postgres:12
    expose:
      - ${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
