# syntax=docker/dockerfile:1
FROM ruby:2.5
#ENV BUNDLER_VERSION=2.1.4
RUN apt-get update -qq && apt-get install -y nodejs npm postgresql-client
RUN npm install --global yarn
WORKDIR /app
COPY ./app_ruby_2_5_9/Gemfile /app/Gemfile
COPY ./app_ruby_2_5_9/Gemfile.lock /app/Gemfile.lock
#RUN gem install bundler -v 2.1.4
RUN bundle install

# Add a script to be executed every time the container starts.
#COPY entrypoint.sh /usr/bin/
#RUN chmod +x /usr/bin/entrypoint.sh
#ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]
